[tools]
# Use the current LTS version of Node.js (after running `mise use node@lts`, run `node --version` to find the specific version)
node = "22.17.0"
# Pin npm version (run `npm --version` to find the specific version)
npm = "10.9.2"

[env]
# Expo CLI environment variables
EXPO_USE_DEV_SERVER = "true"
# Prevent auto-opening browser on expo start
EXPO_NO_BROWSER = "true"

[tasks.start]
run = "npx expo start"
description = "Start Expo development server"

[tasks.build-ios]
run = "npx expo build:ios"
description = "Build for iOS"

[tasks.ios]
run = "npx expo run:ios"
description = "Run on iOS simulator"

[tasks.iphone]
run = "npx expo run:ios --device"
description = "Run on iPhone via USB connection"

[tasks.android]
run = "npx expo run:android"
description = "Run on Android emulator"

[tasks.test]
run = "npm test"
description = "Run tests"

[tasks.lint-fix]
run = "npm run lint:fix"
description = "Fix code quality issues and format with prettier"

[tasks.prettier]
run = "npm run format"
description = "Format code with prettier"
